language: ruby
sudo: false
cache: bundler
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - jruby
matrix:
  include:
    - rvm: 2.2.3
      gemfile: gemfiles/rails_head.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_head.gemfile
