language: ruby
sudo: false
cache: bundler
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3.1'
  - jruby-9.0.4.0
  - rbx
matrix:
  include:
    - rvm: '2.3.0'
      gemfile: gemfiles/rails_head.gemfile
  exclude:
    - rvm: '2.0'
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: '2.1'
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: '2.2'
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 'jruby'
      gemfile: gemfiles/rails_5.0.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_head.gemfile
